on:
  workflow_call:
    inputs:
      name:
        type: string
        description: "The name to say hello to"
        required: true

jobs:
  some-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Output is $_NAME"
        env:
          _NAME: ${{ github.event.inputs.name }}
